version: 2

models:
  - name: stg_addresses
    description: identifying info about each address for order delivery 
    columns:
      - name: address_id
        tests:
          - not_null
  - name: stg_events
    description: event info about each user's web activity
    columns:
      - name: event_id
        tests:
          - not_null
  - name: stg_order_items
    description: order item detail information about each order like product and quantity
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
  - name: stg_orders
    description: identifying info about each completed order like costs, shipping service, delivery estimates and actuals
    columns:
      - name: order_id
        tests:
          - not_null
  - name: stg_products
    description: identifying info about each product like name, price, and inventory count 
    columns:
      - name: product_id
        tests:
          - not_null
  - name: stg_promos
    description: identifying info about each product promo like discount and status 
    columns:
      - name: promo_id
        tests:
          - not_null
  - name: stg_users
    description: identifying info about each created user like first and last name, email and phone numbber, etc.
    columns:
      - name: user_id
        tests:
          - not_null