version: 2

models:
  - name: stg_addresses
    description: identifying info about each address for order delivery 
    columns:
      - name: address_id
        tests:
          - not_null
  - name: stg_events
    description: event info about each user's web activity
    columns:
      - name: event_id
        tests:
          - not_null
  - name: stg_order_items
    description: order item detail information about each order like product and quantity
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
  - name: stg_orders
    description: identifying info about each completed order like costs, shipping service, delivery estimates and actuals
    columns:
      - name: order_guid
        tests:
          - not_null
  - name: stg_products
    description: identifying info about each product like name, price, and inventory count 
    columns:
      - name: product_guid
        tests:
          - not_null
  - name: stg_promos
    description: identifying info about each product promo like discount and status 
    columns:
      - name: promo_id
        tests:
          - not_null
  - name: stg_users
    description: identifying info about each created user like first and last name, email and phone numbber, etc.
    columns:
      - name: user_guid
        tests:
          - not_null
  - name: dim_products
    description: dimesional product table.
    columns:
      - name: product_guid
        tests:
          - not_null
  - name: dim_users
    description: identifying info about each created user like first and last name, email and phone numbber, etc.
    columns:
      - name: user_guid
        tests:
          - not_null
  - name: fact_orders
    description: fact table for orders.
    columns:
      - name: order_guid
        tests:
          - not_null
      - name: user_guid
        tests:
          - not_null
  - name: user_order_facts  
    descriptions: Contains order information at the user level.
    columns:
      - name: user_guid
        tests:
          - not_null
  - name: int_fact_user_orders_agg
    descriptions: Contains summary information at the user level for every user order.
    columns:
      - name: user_guid
        tests:
          - not_null
  - name: int_page_views
    descriptions: Contains page view facts for each session with product pricing information
    columns:
      - name: event_id
        tests:
          - not_null
      - name: session_id
        tests:
          - not_null
  - name: int_fact_product_events_agg
    descriptions: Contains product event counts.
    columns:
      - name: product_guid
        tests:
          - unique
  - name: event_type_aggs
    descriptions: Contains event type aggs per session.
  - name: event_type_agg_prod
    descriptions: Contains event type aggs per session and product_guid.
  - name: int_order_products
    descriptions: Contains event type aggs per session and product_guid. 
  - name: funnel_analysis
    descriptions: Funnel Analyis by date for tracking trend of the three stages
